Fix test snap icons, readmes and snap manifests to be uniform
MetaMask/test-snaps pull request #177
Opened 2023-06-01 22:48 UTC by bowensanders

See #175

2023-06-02 08:53 UTC, FrederikBolding commented on packages/error/README.md
> +A MetaMask Test Snap that throws an error.
```suggestion
A MetaMask Test Snap that throws an out-of-band error.
```

2023-06-02 08:53 UTC, FrederikBolding commented on packages/insights/images/icon.svg
Should we use the template icon for all the test-snaps instead? https://github.com/MetaMask/template-snap-monorepo/blob/main/packages/snap/images/icon.svg

2023-06-02 19:51 UTC, bowensanders commented on packages/insights/images/icon.svg
Updated the icons :)

2023-06-05 08:08 UTC, FrederikBolding approved these changes

2023-06-05 12:05 UTC, FrederikBolding requested changes
Looks like the manifests need to be regenerated after updating the icons.

2023-06-05 16:16 UTC, FrederikBolding approved these changes

2023-06-05 16:16 UTC, merged